[package]
name = "bubble_sort"
version = "0.1.0"
authors = ["Harshaan Babra <harshaan.babra@gmail.com>"]
edition = "2021"

[[bin]]
name = "bubble_sort"
path = "/Users/harshaanbabra/Desktop/Code/Python/leetcode_soltuions/leet_code_solution_in_rust/simple_buble_sort/bubble_sort.rs"


[dependencies]
